name: Build and push my simple web container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Containerfile --tag simple-web-container:latest

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2.5.1
      with:
        image: simple-web-container
        tags: latest
        registry: quay.io/rsoliman/
        username: ${{ secrets.REDHAT_USERNAME }}
        password: ${{ secrets.REDHAT_PASSWORD }} 

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
